Add `deserialize_vec_from_string` function
vityafx/serde-aux pull request #15
Opened 2021-04-01 11:16 UTC by vbrandl

This function allows to deserialize a comma separated `String` into a `Vec<T>`.

`std::str::pattern::Pattern` is unstable but I was thinking about parameterizing over the split pattern as `&str` or a closure and return a `Fn(D) -> Result<Vec<T>, D::Error>>` but ran into lifetime and type errors...

2021-04-02 12:17 UTC, vityafx requested changes
I appreciate the effort and find this extension helpful!
Thank you for your contribution, I surely want to merge this, but there is a little question in the review comments, I'd like to address it with you and then merge the PR.

2021-04-02 12:17 UTC, vityafx commented on src/field_attributes.rs
> +pub fn deserialize_vec_from_string<'de, T, D>(deserializer: D) -> Result<Vec<T>, D::Error>
So the idea here is to allow deserialisation of both, strings and vectors, correct? I think the name should then be reflecting this explicitly, like `deserialize_vec_from_string_or_vec` and still do two things, or left named that way (`deserialize_vec_from_string`) and deal only with strings and not vectors.

2021-04-02 12:28 UTC, vbrandl commented on src/field_attributes.rs
> +pub fn deserialize_vec_from_string<'de, T, D>(deserializer: D) -> Result<Vec<T>, D::Error>
You are right. I want to be able to serialize both strings and lists into a Vec. My concrete usecase would be using the `config` crate, have a setting `cors_allowed_hosts` which is a vec, and be able to configure this using an environment variable like this: `CORS_ALLOWED_HOSTS="example.com,foo.example.com,bar.example.com"`

I renamed the function.

2021-04-02 12:31 UTC, vbrandl commented
One more question about internals of the function: should the elements of the split be `trim`med before calling `from_str`?

Currently `1, 2, 3` cannot be parsed, since the elements would be `["1", " 2", " 3"]` (notice the leading spaces for `2` and `3`). Calling `trim()` before `from_str` would fix this.

On the other hand trimming the string might lose significant whitespace...

2021-04-05 11:48 UTC, vityafx approved these changes

2021-04-05 11:48 UTC, merged

2021-04-05 11:48 UTC, vityafx commented
Thanks!

2021-04-05 12:06 UTC, vbrandl commented
You're right. Maybe something like this would help:

```rust
pub fn foo<'de, T, D, E>(
    sep: impl Fn(char) -> bool,
    parser: impl Fn(&str) -> Result<T, E>
) -> impl Fn(D) -> Result<Vec<T>, <D as serde::Deserializer<'de>>::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
    E: std::fmt::Display
{
  ...
}
```

This way, if `T` implements `FromStr` and that's the desired behavior, this can be called as `foo(|c| c == ',', T::froim_str)`

And if the caller wants the elements to be stripped first, it can be done like this: `foo(|c| c == ',', |s| s.trim().parse::<T>())`

Also this way, we can lose the `T: FromStr` restriction.