serde aux function to get names for fields as they are serialized
vityafx/serde-aux pull request #20
Opened 2021-09-06 12:43 UTC by ta32

from https://github.com/serde-rs/serde/issues/1110

Do you prefer a different method name?

I combined the function to get the field names from structs and enums so its easier to use.  It was possible to use the wrong method for the type for the original implementation. 

I will try address any comments.

2021-09-06 12:54 UTC, vityafx requested changes
Looks simple and fine with me. Probably we will just need to remove one line and address the clippy and formatting issues if they arise during the pipelines. Once everything is done, I'll merge. Thank you!

2021-09-06 12:54 UTC, vityafx commented on src/lib.rs
> +#[macro_use] extern crate serde;
This is not necessary, you may safely remove this line.

2021-09-06 12:54 UTC, vityafx commented on src/serde_introspection.rs
> +    let _ = T::deserialize( EnumVariantsDeserializer{ variants: &mut serialized_names });
Extra space is used as a delimiter, but `rustfmt` will warn about this anyway.

2021-09-06 12:56 UTC, vityafx commented
There are some unsuccessful pipelines. I suggest you run `cargo clippy` and `cargo fmt` locally and that will help you solve everything easily.

2021-09-06 13:50 UTC, ta32 commented on src/lib.rs
> +#[macro_use] extern crate serde;
cargo fmt, just re-arranged it for me. However removing it results in a cargo build & cargo test build error.

2021-09-06 15:13 UTC, vityafx commented on src/lib.rs
> +#[macro_use] extern crate serde;
If you remove this line and make use of scoped macros feature, you'll have it built just fine.

Changes the places where you use `forward_to_deserialize_any!` to `serde::forward_to_deserialize_any!` and just remove this `extern crate` line  :-)

2021-09-08 07:49 UTC, vityafx reviewed
Looks fine in general, I can perform the minor fixes myself should you prefer.
Thank you for your contribution! :-)

2021-09-08 07:49 UTC, vityafx commented on src/lib.rs
> +/// Contains helpers to get serialization names for struct fields and enum variants as they are serialized.
I think the comment may be more generic. For now, it contains only this, yes, but what stops us from extending the module for having more functionality related to "serde introspection"? Perhaps, something like `"Contains helpers for accessing structure metadata (e.g. fields) using serde"`?

2021-09-08 07:49 UTC, vityafx commented on src/serde_introspection.rs
> +/// # Example:
Please change to `# Example`.

2021-09-08 07:49 UTC, vityafx commented on src/serde_introspection.rs
> +/// Gets the serialization names for structs and enums
Please add the finishing dot after the sentence :)

2021-09-08 11:24 UTC, ta32 commented
Sure, edits by maintainer is checked for this PR.  

I didn't understand what you meant by the removing example colon so I left that to you. 
Feel free to make any more edits if you need to thanks :)

2021-09-08 11:37 UTC, vityafx commented
> Sure, edits by maintainer is checked for this PR.
> 
> I didn't understand what you meant by the removing example colon so I left that to you, I saw it in other places?
> Feel free to make any more edits if you need to thanks :)

Yes, so in "cool" markdown, the colons after headers aren't welcomed, just a style. For example, [here](https://docs.rs/hyper/0.14.12/hyper/index.html) you won't see `:` after `features` or `Optional features` headers.

2021-09-08 11:37 UTC, vityafx commented
I'll merge once the checks are done. Thanks again!

2021-09-08 11:59 UTC, merged

2021-09-08 18:49 UTC, vityafx commented on src/serde_introspection.rs
> +/// # Example:
I'll change myself.